NBISweden/predictprotein-webserver-topcons2

- proj/cgi-bin/restart_qd_fe.cgi
- proj/pred/app/qd_fe.py
Merge the SubmitJob function with the library libpredweb
> Feat: use SubmitJob from libpredweb

- proj/pred/app/qd_fe.py
Use the function CheckIfJobFinished from libpredweb
> feat: use checkIfJobFinished module from libpredweb

- proj/pred/app/qd_fe.py
Use the function GetNumSeqSameUserDict from libpredweb
> feat: use GetNumSeqSameUserDict from libpredweb

- proj/pred/app/qd_fe.py
> refactor: clean unused functions

- proj/pred/app/qd_fe.py
Use the function CreateRunJoblog from libpredweb
> Feat: use createrunjoblog from libpredweb

- proj/pred/app/qd_fe.py
Add necessary g_parameters for running checkIfJobFinished in a separate process
> feat: add g parameters

- proj/pred/app/qd_fe.py
Use threshold_logfilesize from g_params
> fix: undefined threshold_logfilesize

- proj/pred/views.py
use the function SubmitQueryToLocalQueue() from libpredweb
> Feat: use submit query to local queue from libpredweb

- proj/pred/templates/pred/help.html
- proj/pred/templates/pred/submit_seq.html
This PR addresses [issue #16](https://github.com/NBISweden/SysDev-Maple/issues/16).
The acknowledgment is updated to 
> This work used the <a href="https://www.egi.eu/infrastructure/cloud/">EGI infrastructure</a> with the support of IN2P3-IRES, INFN-CLOUD-BARI and TR-FC1-ULAKBIM.
> feat: update acknowledgements

- setup_virtualenv.sh
This PR fix the set up script so that activate_this.py wil be created
> fix: setup scripts

- proj/pred/templates/pred/egi_acknowledgement.html
- proj/pred/templates/pred/help.html
- proj/pred/templates/pred/submit_seq.html
Refactor to use the template file for the egi acknowledgment.
> refactor: use template for egi acknowledgment

- proj/pred/templates/pred/help.html
> fix: duplicated header index

- proj/pred/app/qd_fe.py
This PR enables the qd_fe to use GetResult function from libpredweb.
> Feat: use GetResult from libpredweb

- proj/pred/app/run_job.py
This PR fixes the import problem of libpredweb in `run_job.py`
> fix: import problem

- proj/pred/templates/pred/submit_seq.html
> feat: clarify notification for the sequence length

- proj/pred/app/qd_fe.py
This PR updates the syntax to use CleanCachedResult() from libpredweb
> Feat: update syntax for clean cached result

- Dockerfile
- docker-compose.yml
- dockerrun.sh
- proj/docker_settings.py
- proj/wsgi.py
This PR closes issue #40.
Usage:
`docker compose build`
`docker compose up`
The web page will be available at port `8000`.
> chore: dockerize

- proj/pred/templates/pred/base_layout.html
- proj/pred/templates/pred/serverstatus.html
- proj/pred/views.py
This PR together with https://github.com/NBISweden/libpredweb/pull/46 closes https://github.com/NBISweden/libpredweb/issues/20
Please have a look at http://dev.topcons.bioshu.se/pred/serverstatus/ to see the new interactive graphs. If you would like you can compare with the old png:s at https://topcons.cbr.su.se/pred/serverstatus/.
> feat: server statistics graph

- proj/wsgi.py
> fix: broken wsgi settings

- proj/pred/templates/pred/download.html
- proj/pred/views.py
This PR closes https://github.com/NBISweden/SysDev-Maple/issues/19
Changes made
The database on the server pcons1 has been updated 
The download page shows more information of the database
> feat: update the download page show db info

- proj/api/views.py
> fix: exclude submit_date if timezone info is not available

- requirements.txt
> change dep branch from master to main

- init.sh
- requirements.txt
This PR closes #95 
The settings tuned for the new frontend server pcons4 is updated on the Github.
> Fix settings for pcons4

- proj/pred/templates/pred/get_results_eachseq.html
- proj/pred/views.py
This PR closes #100 
When the sequence is submitted to the remote queue, the queue time will be shown instead of a blank page
> Feat: show remote queue time

- proj/pred/static/css/template_css.css
- proj/pred/templates/pred/base_layout.html
> adjust right panel width and table config

- proj/pred/static/doc/news.txt
This PR closes #108 
Add the news about the recent database updating
The link to the database in the download page is also included
> add news about the database updating
